import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  screen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  listContainer: {
    backgroundColor: 'white',
    width: 300,
    height: '100%',
    marginVertical: 10,
    padding: 10,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#820263',
    shadowColor: '#2E294E',
    shadowOffset: { width: 1, height: 1 },
    shadowRadius: 1,
    shadowOpacity: 0.3,
    elevation: 1,
  },
  waitingList: {
    height: '65%',
    width: '100%',
  },
  background: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: '100%',
  },
  roomCode: {
    fontSize: 30,
    marginVertical: 10,
    fontFamily: 'LilitaOne',
    color: '#2E294E',
  },
  usernameContainer: {
    minWidth: '80%',
    alignItems: 'center',
    borderBottomColor: '#2E294E',
    borderBottomWidth: 1,
    padding: '2%',
  },
  usernames: {
    fontSize: 22,
    marginVertical: 10,
    fontFamily: 'LilitaOne',
    color: '#2E294E',
    textAlign: 'center',
    margin: 60,
  },
  button: {
    marginBottom: 100,
  },
  box: {
    width: 300,
    height: '65%',
    alignItems: 'center',
    position: 'relative',
    marginVertical: 20,
  },
  subBox: {
    position: 'absolute',
    top: -5,
    backgroundColor: '#2E294E',
    paddingHorizontal: 18,
    borderRadius: 10,
    alignItems: 'center',
    zIndex: 20,
  },
  subhead: {
    fontSize: 13,
    fontWeight: '600',
    color: 'white',
    marginVertical: 10,
    textTransform: 'uppercase',
  },
});
